package sample.entity;
// Generated Oct 19, 2016 10:15:15 AM by Hibernate Tools 4.3.1



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private String userName;
     private String password;
     private String hoten;
     private String gioiTinh;
     private String email;
     private String role;

    public Customers() {
    }

    public Customers(String userName, String password, String hoten, String gioiTinh, String email, String role) {
       this.userName = userName;
       this.password = password;
       this.hoten = hoten;
       this.gioiTinh = gioiTinh;
       this.email = email;
       this.role = role;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


